object ActorType {
+ id [1-1]: uuid
+ actorCode [1-1]: String
+ contactPerson [1-1]: personType:id
+ organisation [1-1]: organisationType:id
--
This is a simplified model showing only relevant fields. 
Please refer to the full Entity diagram for details
}